# Generated by Django 6.0.2 on 2026-02-28 01:17

import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Great Britain Pound')], default='USD', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(currency_choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Great Britain Pound')], decimal_places=2, default_currency='USD', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
