# Generated by Django 6.0.2 on 2026-02-28 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reference',
            field=models.TextField(unique=True),
        ),
    ]
