# Generated by Django 6.0.2 on 2026-03-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_user_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='balance_currency',
        ),
    ]
