# Generated by Django 6.0.2 on 2026-03-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_alter_ledger_account_id_alter_ledger_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
